# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180728_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Posts'},
        ),
    ]
